sudo: required
language: python
services:
  - docker
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - docker-compose -f tests/server_dir/docker-compose.yml up -d
install:
  - pip install coverage 
  - pip install mock
  - pip install netaddr
  - pip install flake8
  - pip install codecov
  - python setup.py install
script:
  - flake8 --ignore=E501,E402,F401,W504 src tests
  - coverage run --append -m unittest discover -v -s tests/
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' && $TRAVIS_BRANCH == 'master' ]]; then codecov; fi
deploy:
  provider: pypi
  user: x4vi_mendez
  password:
    secure: A2BrU6qqQHSrJ7jvxOSr1/l4HdHT5EvRWvkufMR+kdq8I8qgTlGio22Tc4OSrD5Oe7Zz7ST7q3fJFRf8Kt/gdZp7DJeeVR5gK113EvquYQUdb+wbKiBHQ3hu7JBWAjrzUQ3mDPk5DJN77dUVByYoZUmWQVMyg2fmUnQxRdertLI=
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch: travis_pypi
    python: 3.6
